version: '3.8'

services:
  userservice:
    build: ./user-service
    container_name: user-service-app
    ports: 
      - "8081:8081"
    environment:
      # Iska naam wahi hona chahiye jo application.yaml mein ${} ke andar hai
      - MONGODB_URI=
      
      # JWT logic: Base64 secret key for internal auth
      - JWT_SECRET=tKATROyt2Yb66TxRjagQ5lt5OmPdythS2oSHfw7wzb0=
      - JWT_EXPIRATION=86400000
      - JWT_REFRESH_EXPIRATION=604800000
      
      # CORS: Taaki tumhara frontend (React/Angular) isse baat kar sake
      - CORS_ALLOWED_ORIGINS=*
      
      # Seeding Logic: Pehli baar run hone par default admin banane ke liye
      - SEED_ADMIN_EMAIL=admin@medicalerp.com
      - SEED_ADMIN_PASSWORD=Admin@123456
      - SEED_ORG_NAME=MedERP HQ
      - SEED_ORG_REG_NUMBER=HQ-0001
    networks:
      - my-network

networks:
  my-network:
    driver: bridge